name: Build Bootloader

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install -y binutils-avr avr-libc gcc-avr
    - run: cd optiboot/bootloaders/optiboot && make AVR_FREQ=8000000 SUPPORT_EEPROM=0 TIMEOUT=2 SOFT_UART=1 SOFTTX=B1 SOFTRX=B2 LED_START_FLASHES=0 LED_DATA_FLASH=0 LED_START_ON=0 attiny44 && mv optiboot_attiny44.hex icecreamuino_optiboot_attiny44.hex
    - run: cd optiboot/bootloaders/optiboot && make AVR_FREQ=8000000 SUPPORT_EEPROM=0 TIMEOUT=2 SOFT_UART=1 SOFTTX=B1 SOFTRX=B2 LED_START_FLASHES=0 LED_DATA_FLASH=0 LED_START_ON=0 attiny84 && mv optiboot_attiny84.hex icecreamuino_optiboot_attiny84.hex
    - run: cd optiboot/bootloaders/optiboot && make AVR_FREQ=12000000 SUPPORT_EEPROM=1 TIMEOUT=2 SOFT_UART=1 SOFTTX=B7 SOFTRX=F6 LED_START_FLASHES=0 LED_DATA_FLASH=0 LED_START_ON=0 atmega128rfa1 && mv optiboot_atmega128rfa1.hex srxe.hex
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: icecreamuino_bootloader
        path: optiboot/bootloaders/optiboot/icecreamuino*.hex
        if-no-files-found: error
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: srxe_bootloader
        path: optiboot/bootloaders/optiboot/srxe*.hex
        if-no-files-found: error
